### ISSUE TITLE
crashes on incoming e-mail

### ISSUE THREAD

**Issue by Finkregh** [hamin/kyatchi#5]
start kyatchi (error happens as soon as en email comes in:

```
$ npm start kyatchi

> kyatchi@0.0.2 start /home/node/node_modules/kyatchi
> coffee app.coffee 

SMTP server running on port 1025
Kyatchi web interface started on port 1080

/home/node/node_modules/kyatchi/app.coffee:44
          from: parsedEmail.header.from.value,
                                       ^
TypeError: Cannot read property 'value' of undefined
    at MessageStream.<anonymous> (/home/node/node_modules/kyatchi/app.coffee:44:40)
    at MessageStream.emit (events.js:61:17)
    at Server.<anonymous> (/home/node/node_modules/kyatchi/node_modules/smtp/lib/smtp.js:126:13)
    at Socket.<anonymous> (native)
    at Socket.emit (events.js:64:17)
    at unspool (/home/node/node_modules/kyatchi/node_modules/smtp/lib/smtp.js:70:11)
    at Socket.<anonymous> (/home/node/node_modules/kyatchi/node_modules/smtp/lib/smtp.js:76:3)
    at Socket.emit (events.js:64:17)
    at Socket._onReadable (net.js:673:31)
    at IOWatcher.onReadable [as callback] (net.js:177:10)
npm ERR! kyatchi@0.0.2 start: `coffee app.coffee`
npm ERR! `sh "-c" "coffee app.coffee"` failed with 1
npm ERR!
npm ERR! Failed at the kyatchi@0.0.2 start script.
npm ERR! This is most likely a problem with the kyatchi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     coffee app.coffee
npm ERR! You can get their info via:
npm ERR!     npm owner ls kyatchi
npm ERR! There is likely additional logging output above.
npm ERR!
npm ERR! System Linux 2.6.32-5-amd64
npm ERR! command "node" "/home/node/local/node/bin/npm" "start" "kyatchi"
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/node/npm-debug.log
npm not ok
```

send an e-mail:

```
<-  220 hostname.unconfigured ESMTP node.js
 -> EHLO bar.org
<-  250-hostname.unconfigured
<-  250 HELP
 -> MAIL FROM:<foo@bar.org>                                                                                        
<-  250 MAIL FROM looks good enough for me.                                                                                    
 -> RCPT TO:<ol@foo.org>                                                                                                       
<-  250 RCPT TO ...I hope that's right. I didn't check.)                                                                       
 -> DATA                                                                                                                       
<-  354 Enter mail, end with "." on a line by itself                                                                           
 -> Date: Wed, 22 Jun 2011 09:05:55 +0200                                                                                      
 -> To: ol@foo.org                                                                                                             
 -> From: foo@bar.org                                                                                             
 -> Subject: test Wed, 22 Jun 2011 09:05:55 +0200                                                                              
 -> X-Mailer: swaks v20100211.0 jetmore.org/john/code/swaks/                                                                   
 ->                                                                                                                            
 -> This is a test mailing                                                                                                     
 ->                                                                                                                            
 -> .                                                                                                                          
*** Remote host closed connection unexpectedly.
```

debug.log:

```
$ less npm-debug.log
info it worked if it ends with ok
verbose cli [ 'node',
verbose cli   '/home/node/local/node/bin/npm',
verbose cli   'start',
verbose cli   'kyatchi' ]
info using npm@1.0.13
info using node@v0.4.8
verbose config file /home/node/.npmrc
verbose config file /home/node/local/node/etc/npmrc
silly testEngine { name: 'kyatchi',
silly testEngine   version: '0.0.2',
silly testEngine   description: 'Catch the Mail!',
silly testEngine   keywords: [ 'smtp', 'email', 'mail', 'development' ],
silly testEngine   homepage: 'https://github.com/hamin/kyatchi',
silly testEngine   author:
silly testEngine    { name: 'Haris Amin',
silly testEngine      email: 'aminharis7@gmail.com',
silly testEngine      url: 'http://github.com/hamin' },
silly testEngine   directories: { lib: './lib' },
silly testEngine   scripts: { start: 'coffee app.coffee' },
silly testEngine   repository:
silly testEngine    { type: 'git',
silly testEngine      url: 'git://github.com/hamin/kyatchi.git' },
silly testEngine   dependencies:
silly testEngine    { 'coffee-script': '>=1.1.1',
silly testEngine      express: '>= 2.3.10',
silly testEngine      jade: '>= 0.12.0',
silly testEngine      faye: '>=0.6',
silly testEngine      smtp: '>= 0.1.0' },
silly testEngine   engines: { node: '>= 0.4.7' },
silly testEngine   _npmJsonOpts:
silly testEngine    { file: '/home/node/node_modules/kyatchi/package.json',
silly testEngine      wscript: false,
silly testEngine      contributors: false,
silly testEngine      serverjs: false },
silly testEngine   _id: 'kyatchi@0.0.2',
silly testEngine   devDependencies: {},
silly testEngine   _engineSupported: true,
silly testEngine   _npmVersion: '1.0.13',
silly testEngine   _nodeVersion: 'v0.4.8',
silly testEngine   _defaultsLoaded: true }
verbose caching /home/node/node_modules/kyatchi/package.json
verbose loadDefaults kyatchi@0.0.2
verbose run-script [ 'prestart', 'start', 'poststart' ]
info prestart kyatchi@0.0.2
info start kyatchi@0.0.2
verbose unsafe-perm in lifecycle true
silly exec sh "-c" "coffee app.coffee"
info kyatchi@0.0.2 Failed to exec start script
ERR! kyatchi@0.0.2 start: `coffee app.coffee`
ERR! `sh "-c" "coffee app.coffee"` failed with 1
ERR!
ERR! Failed at the kyatchi@0.0.2 start script.
ERR! This is most likely a problem with the kyatchi package,
ERR! not with npm itself.
ERR! Tell the author that this fails on your system:
ERR!     coffee app.coffee
ERR! You can get their info via:
ERR!     npm owner ls kyatchi
ERR! There is likely additional logging output above.
ERR!
ERR! System Linux 2.6.32-5-amd64
ERR! command "node" "/home/node/local/node/bin/npm" "start" "kyatchi"
verbose exit [ 1, true ]
```

what other info do you need?

**Comment by hamin** [comment]
what version of node and npm are you runnning?

**Comment by hamin** [comment]
@Finkregh i just published a new version of kyatchi, uninstall the current version and install the new version. Let me know if it solves your problem.

**Comment by Finkregh** [comment]
still some problem:

```
$ npm start kyatchi

> kyatchi@0.0.3 start /home/node/node_modules/kyatchi
> coffee app.coffee

SMTP server running on port 1025
Kyatchi web interface started on port 1080



/home/node/node_modules/kyatchi/app.coffee:51
            plain: parsedEmail.body[1].body[0].content,
                                      ^
TypeError: Cannot read property 'body' of undefined
    at MessageStream.<anonymous> (/home/node/node_modules/kyatchi/app.coffee:51:39)
    at MessageStream.emit (events.js:61:17)
    at Server.<anonymous> (/home/node/node_modules/kyatchi/node_modules/smtp/lib/smtp.js:126:13)
    at Socket.<anonymous> (native)
    at Socket.emit (events.js:64:17)
    at unspool (/home/node/node_modules/kyatchi/node_modules/smtp/lib/smtp.js:70:11)
    at Socket.<anonymous> (/home/node/node_modules/kyatchi/node_modules/smtp/lib/smtp.js:76:3)
    at Socket.emit (events.js:64:17)
    at Socket._onReadable (net.js:673:31)
    at IOWatcher.onReadable [as callback] (net.js:177:10)
npm ERR! kyatchi@0.0.3 start: `coffee app.coffee`
npm ERR! `sh "-c" "coffee app.coffee"` failed with 1
[...]
```

```
$ node -v
v0.4.8
$ npm -v
1.0.13
```

**Comment by hamin** [comment]
I think it might be an issue with the smtp client you are testing with ( I think it's jetmore.org/john/code/swaks/  )

Can you try a simple telnet test like this:

Type 'telnet localhost 1025' in a shell and then enter each one of these lines below

<pre>
HELO example.com
MAIL FROM:youremailaddres@example.com
RCPT TO:youremailaddres@example.com
DATA
From: youremailaddres@example.com
To: youremailaddres@example.com
Subject: Test
This is a test.
.
QUIT
</pre>

**Comment by Finkregh** [comment]
i ran a test with your data and got an error, too:

```
$ npm start kyatchi

> kyatchi@0.0.3 start /home/node/node_modules/kyatchi
> coffee app.coffee

SMTP server running on port 1025
Kyatchi web interface started on port 1080

/home/node/node_modules/kyatchi/app.coffee:49
          created_at: parsedEmail.header.date.value,
                                             ^
TypeError: Cannot read property 'value' of undefined
    at MessageStream.<anonymous> (/home/node/node_modules/kyatchi/app.coffee:49:46)
    at MessageStream.emit (events.js:61:17)
    at Server.<anonymous> (/home/node/node_modules/kyatchi/node_modules/smtp/lib/smtp.js:126:13)
    at Socket.<anonymous> (native)
    at Socket.emit (events.js:64:17)
    at unspool (/home/node/node_modules/kyatchi/node_modules/smtp/lib/smtp.js:70:11)
    at Socket.<anonymous> (/home/node/node_modules/kyatchi/node_modules/smtp/lib/smtp.js:76:3)
    at Socket.emit (events.js:64:17)
    at Socket._onReadable (net.js:673:31)
    at IOWatcher.onReadable [as callback] (net.js:177:10)
npm ERR! kyatchi@0.0.3 start: `coffee app.coffee`
npm ERR! `sh "-c" "coffee app.coffee"` failed with 1
npm ERR!
npm ERR! Failed at the kyatchi@0.0.3 start script.
npm ERR! This is most likely a problem with the kyatchi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     coffee app.coffee
npm ERR! You can get their info via:
npm ERR!     npm owner ls kyatchi
npm ERR! There is likely additional logging output above.
npm ERR!
npm ERR! System Linux 2.6.32-5-amd64
npm ERR! command "node" "/home/node/local/node/bin/npm" "start" "kyatchi"
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/node/npm-debug.log

```

**Comment by hamin** [comment]
@Finkregh ignore my telnet test, i think your original test was right, i'm working on the fix, sorry for the delay

**Comment by hamin** [comment]
@Finkregh i just published version 0.0.4, this should fix the problem. If the same problem still persist let me know. Remember, IGNORE MY TELNET TEST :) I was able to recreate your original problem using an smtp test client. Let me know if this is working for you or not now.

**Comment by hamin** [comment]
@Finkregh btw, the problem was I was not properly handling NON-multipart email messages :)

**Comment by Finkregh** [comment]
well, well, glad i could help ;)

**Comment by Finkregh** [comment]
something changed, please reopen:

```
$ npm start kyatchi

> kyatchi@0.0.4 start /home/node/node_modules/kyatchi
> coffee app.coffee

SMTP server running on port 1025
Kyatchi web interface started on port 1080

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
TypeError: undefined is not a function
    at CALL_NON_FUNCTION (native)
    at /home/node/node_modules/kyatchi/node_modules/libnotify/lib/libnotify.js:61:21
    at /home/node/node_modules/kyatchi/node_modules/libnotify/lib/libnotify.js:26:14
    at ChildProcess.exithandler (child_process.js:106:7)
    at ChildProcess.emit (events.js:67:17)
    at Socket.<anonymous> (child_process.js:172:12)
    at Socket.emit (events.js:64:17)
    at Array.<anonymous> (net.js:831:12)
    at EventEmitter._tickCallback (node.js:126:26)
npm ERR! kyatchi@0.0.4 start: `coffee app.coffee`
npm ERR! `sh "-c" "coffee app.coffee"` failed with 1
```

**Comment by hamin** [comment]
hmm... what operating system are you running kyatchi in?

**Comment by Finkregh** [comment]
debian stable/squeeze, 2.6.32-5-amd64

node is v0.4.8
kyatchi@0.0.4 ./kyatchi 
├── growl@1.1.0
├── libnotify@1.0.2
├── coffee-script@1.1.1
├── jade@0.12.4
├── smtp@0.1.4
├── faye@0.6.2 (redis@0.6.4)
└── express@2.4.0

**Comment by hamin** [comment]
do you have libnotify installed, its an apt pacakage, you need that in order for desktop notifications to work

**Comment by Finkregh** [comment]
well, i thought that it would be possible to run kyatchi on a server (where i would net like to install something like libnotify+deps).
Is it possible to make notifications via libnotify optional?

**Comment by hamin** [comment]
hmm, it isn't as of right now, but i will work on it, i need to work on removing the coffeescript dependency (which I've been meaning to do for a while) and add proper arguments for stuff like smtp and app ports you want kyatchi to run on. When I do that, i can also add an argument that you can pass to turn off desktop notifications. I'll let you know when i've implemented that. But this thread/issue is officially closed :)
